# This file was generated by Gemini 3.1 Pro (High) using the Generate Quest Data steps in architecture.md
# The content of this file is not intended to be used by the system but simply for reference and analysis.
# No database data was used, all data was generated by the LLM.
quest_data = {
    "party_level": 1,
    "player_count": 4,
    "theme": "Dark Fantasy / Mystery",
    "setting": "A remote, fog-shrouded logging village.",
    
    # Generated in Step 4
    "plot_hook": "The party is hired to investigate a series of disappearances in the logging village of Oakhaven, only to discover the villagers are hiding a dark pact with a creature of the woods.",
    
    # Generated in Step 5
    "summary": "The party arrives in Oakhaven and uncovers the villagers' secret. They must navigate a tense social situation to discover the location of the creature's lair, survive a treacherous journey into the cursed woods, and finally confront the creature to break the pact.",
    
    # Generated in Steps 6-9
    "acts": [
        {
            "act_number": 1,
            "summary": "The Setup. The party arrives in Oakhaven and begins questioning the suspicious locals, eventually learning about the 'Whispering Woods'.",
            "scenes": [
                {
                    "scene_number": 1,
                    "introduction": "The party arrives at the village gates as evening approaches.",
                    "summary": "The party tries to gain entrance to the village and secure lodging at the local tavern, but the guards are highly suspicious of outsiders.",
                    "resolution": "The party secures a room and learns that no one goes into the woods after dark.",
                    "time_of_day": "Evening",
                    "time_passed": "0 hours",
                    "rest_opportunity": "Long Rest (8 hours) at the tavern.",
                    
                    # Generated in Steps 15-16
                    "location": {
                        "name": "The Rusty Axe Tavern",
                        "description": "A dimly lit, smoke-filled tavern that smells of wet dog and stale ale. The patrons go dead silent as you walk in."
                    },
                    
                    # Generated in Steps 17-18
                    "npcs": [
                        {
                            "name": "Garret Ironbark",
                            "ancestry": "Human",
                            "class_or_profession": "Tavern Keeper",
                            "level": 1,
                            "skills": {"Diplomacy": 5, "Deception": 7, "Society": 5},
                            "saves": {"Fortitude": "High", "Reflex": "Low", "Will": "Medium"},
                            "perception": 5,
                            "personality": "Gruff, paranoid, but greedy enough to accept coin from strangers.",
                            "appearance": "A burly man with a thick beard and a nervous twitch in his left eye.",
                            "background": "Lived in Oakhaven his whole life; secretly helped cover up the first disappearance."
                        }
                    ],
                    
                    # Generated in Steps 19-22
                    "encounter": {
                        "type": "social",
                        "threat_level": "Low",
                        "xp_value": 60,
                        "introduction": "Garret stands behind the bar, polishing a dirty glass, eyeing you with overt suspicion.",
                        "resolution": "Garret begrudgingly hands over the room keys and mutters a warning.",
                        "event_details": {
                            "influence_data": [
                                {
                                    "npc_name": "Garret Ironbark",
                                    "discovery": ["Society", "Perception"],
                                    "influence": {"Diplomacy": 15, "Intimidation": 13, "Deception": 15},
                                    "thresholds": {
                                        "4": "Minor Boon: Gives the party a room.",
                                        "6": "Moderate Boon: Gives the party a room at half price.",
                                        "8": "Major Boon: Warns the party specifically about the 'Whispering Woods'."
                                    },
                                    "resistances": "Appeals to his morality (-2 to rolls).",
                                    "weaknesses": "Bribes or displays of wealth (+2 to rolls).",
                                    "penalty": "Asking directly about the disappearances removes 1 turn."
                                }
                            ]
                        },
                        "reward": {
                            "treasure_value": 0,
                            "boons": ["Allowed to rest at the tavern", "Learned about the Whispering Woods"],
                            "key_items": []
                        }
                    }
                }
            ]
        },
        {
            "act_number": 2,
            "summary": "The Confrontation. The party travels into the Whispering Woods, facing natural hazards and corrupted wildlife.",
            "scenes": [
                {
                    "scene_number": 2,
                    "introduction": "The party leaves the village at dawn and enters the thick, fog-choked woods.",
                    "summary": "The party must navigate the treacherous terrain and find the creature's lair without getting hopelessly lost.",
                    "resolution": "The party successfully navigates the woods and discovers the entrance to a ruined crypt.",
                    "time_of_day": "Morning",
                    "time_passed": "8 hours (Long Rest)",
                    "rest_opportunity": "Short Rest (10 minutes) before entering the crypt.",
                    
                    "location": {
                        "name": "The Whispering Woods",
                        "description": "Ancient, twisted trees claw at the sky. A thick fog obscures vision beyond 30 feet, and strange whispers seem to echo from nowhere."
                    },
                    "npcs": [],
                    
                    "encounter": {
                        "type": "skill_challenge",
                        "threat_level": "Moderate",
                        "xp_value": 80,
                        "introduction": "The path disappears into the undergrowth. You'll need your wits to find the way.",
                        "resolution": "You burst through a thicket of briars and find yourselves staring at a stone archway leading underground.",
                        "event_details": {
                            "victory_points_required": 15,
                            "obstacles": [
                                {
                                    "description": "A deep, rushing stream swollen with recent rains blocks the path.",
                                    "skills": {"Athletics": 18, "Nature": 16, "Survival": 16},
                                    "success_resolution": "The party finds a safe ford or creates a makeshift bridge.",
                                    "failure_resolution": "The party is swept down stream, taking 1d6 bludgeoning damage and losing time."
                                }
                                # ... additional obstacles ...
                            ]
                        },
                        "reward": {
                            "treasure_value": 15, # Found some loose coins in the stream
                            "boons": ["Arrive at the crypt without being Fatigued"],
                            "key_items": ["A tarnished silver locket (clue to the creature's identity)"]
                        }
                    }
                }
            ]
        },
        {
            "act_number": 3,
            "summary": "The Resolution. The party delves into the crypt and battles the creature.",
            "scenes": [
                {
                    "scene_number": 3,
                    "introduction": "You step into the damp, lightless crypt.",
                    "summary": "The party fights the creature of the woods and its corrupted minions.",
                    "resolution": "The creature falls, and the dark pact holding the village hostage is broken.",
                    "time_of_day": "Afternoon",
                    "time_passed": "4 hours (Travel)",
                    "rest_opportunity": "None. The quest is complete.",
                    
                    "location": {
                        "name": "The Ruined Crypt",
                        "description": "A subterranean chamber filled with the stench of decay. Bones litter the floor."
                    },
                    "npcs": [],
                    
                    "encounter": {
                        "type": "combat",
                        "threat_level": "Severe",
                        "xp_value": 120,
                        "introduction": "A massive, corrupted beast emerges from the shadows, eyes glowing with malevolent intelligence.",
                        "resolution": "With a final, echoing roar, the beast collapses.",
                        "event_details": {
                            "enemies": [
                                {
                                    "name": "Corrupted Woodbeast",
                                    "level": 3,
                                    "xp_cost": 80,
                                    "role": "Boss"
                                },
                                {
                                    "name": "Blight Zombie",
                                    "level": -1,
                                    "xp_cost": 20,
                                    "role": "Minion"
                                },
                                {
                                    "name": "Blight Zombie",
                                    "level": -1,
                                    "xp_cost": 20,
                                    "role": "Minion"
                                }
                            ]
                        },
                        "reward": {
                            "treasure_value": 160, # Boss loot
                            "boons": [],
                            "key_items": ["The Beast's Heart (proof for the villagers)"]
                        }
                    }
                }
            ]
        }
    ]
}
